modLoader="javafml" #mandatory

loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="${mod_license}"

issueTrackerURL="https://github.com/Tiviacz1337/Warrior-Rage/issues"

logoFile="assets/warriorrage/logo.png"

[[mods]] #mandatory

modId='${mod_id}' #mandatory

version="${mod_version}" #mandatory

displayName="${mod_display_name}" #mandatory

displayURL="https://www.curseforge.com/minecraft/mc-mods/warrior-rage"

authors="${mod_authors}"

description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"