
modLoader="javafml"

loaderVersion="[42,)"

license="All Rights Reserved"

issueTrackerURL="https://github.com/Tiviacz1337/Warrior-Rage/issues"

logoFile="assets/warriorrage/logo.png"

[[mods]]

modId="warriorrage"

version="1.2.3"

displayName="Warrior Rage"

updateJSONURL=""

displayURL="https://www.curseforge.com/minecraft/mc-mods/warrior-rage"

authors="Tiviacz1337"

description='''
Brings Kill Streak functionality to combat.
'''

[[dependencies.warriorrage]]
    modId="forge"
    mandatory=true
    versionRange="[42,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.warriorrage]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.1, 1.20)"
    ordering="NONE"
    side="BOTH"
